### PR TITLE
addTimeZone

### PR DESCRIPTION
**Pull request by caiyuan1222**
1. Admin can select the time zone when they create an announcement, so we can use this time zone to change as UTC string. Only take a four-time zone across U.S. now. 
2. When loading the page, we convert all those time as local time. 
3. I cannot create the new announcement, are we still allowed to create now? Want to test the landing page.

### CODE REVIEW

**Comment by davidmjiang** [comment]
What issue are you running into when trying to create the announcement?

**Comment by davidmjiang** [comment]
A few observations:
1. Need to pass in timezone to the Card components in CreatePsa.jsx so that it shows up in the mobile preview and confirmation page.
2. Timezones are hardcoded as PDT, EDT, etc. What happens when daylight savings ends in November? I think you may want do some research into what external libraries or browser APIs are available to help with this

**Comment by caiyuan1222** [comment]
> A few observations:
> 
> 1. Need to pass in timezone to the Card components in CreatePsa.jsx so that it shows up in the mobile preview and confirmation page.
> 2. Timezones are hardcoded as PDT, EDT, etc. What happens when daylight savings ends in November? I think you may want do some research into what external libraries or browser APIs are available to help with this

**Comment by caiyuan1222** [comment]
Hello @davidmjiang 

For the question 
1. I believe I have added timeZone in createPSA file. 
2. To my understanding, as user provides timeZone, javascript could detect the time saving.

Attach a picture to better understand:
The senario is user select 9:00 am to 6:00pm in EST time, which is 3 hours ahead for the PDT time. Since I was in PDT time, so the card will show the time based on my location and also indicate the time zone. 
image

**Review by kgao — COMMENTED** [review]
Look good to me, defer to @davidmjiang

**Comment by davidmjiang** [comment]
I am trying to understand the picture. Is the EDT time in gray shown for testing purposes and 6:00am-3:00pm is what actually shows up on the card? As for daylight savings, it will change from PDT for example to PST, so will we handle that?

**Comment by caiyuan1222** [comment]
yes, David! the gray is when I create the announcement, I take 9:00 am to 6:00pm EDT. Since I was in PDT time, so the card will show 6:00am to 3:00pm PDT (the card will always show the local time). Oh, I see. after day saving, it should be PST? I did not realize it will change as PST. will add more conditions.

**Comment by caiyuan1222** [comment]
https://stackoverflow.com/questions/11887934/how-to-check-if-dst-daylight-saving-time-is-in-effect-and-if-so-the-offset 
add link for better explanation

**Review by davidmjiang — APPROVED** [review]

**Pull request merged**
